### ISSUE TITLE
Test is failling on master branch

### ISSUE THREAD

**Issue by mancellin** [LHEEA/meshmagick#11]
On the current master branch (tag 1.0.5), `meshmagick/tests/test_IO.py` is failing in `load_DAT`. 
It was successful in the previous tagged version 1.0.4.

**Comment by mancellin** [comment]
Actually, you might already be aware of it: https://travis-ci.org/LHEEA/meshmagick/jobs/566975589

**Comment by frongere** [comment]
Fixed, thanks for pointing it out
