### ISSUE TITLE
NaN normals when writing mesh object to stl file

### ISSUE THREAD

**Issue by ahmedmetin** [LHEEA/meshmagick#13]
Hello, 

I get NaN values when writing mesh to stl file. The python mesh object does not have nan values but when saved to stl, NaN values appear in normals. 

Best regards,
Ahmed

**Comment by ahmedmetin** [comment]
It happens when there duplicate vertices it seems. 
  facet normal             nan            nan            nan
    outer loop
      vertex   0.000000e+00   0.000000e+00  -2.144183e+00
      vertex   0.000000e+00   0.000000e+00  -2.144183e+00
      vertex  -5.000000e-01   8.660254e-01  -2.144183e+00
    endloop
  endfacet

which cause 0 normal vector.

Then there is 
        n = np.cross(v1 - v0, v2 - v0)
        n /= np.linalg.norm(n)

in write_STL function, which causes the problem I think. 
Is there a way to eliminate the duplicate vertices in meshmagick?

**Comment by frongere** [comment]
From what I can see on your last post, the triangle you show seems to be collapsed. Two of its vertices are at the same position so the triangle does not represent a plane but a line. The normal is then undefined and you get NaN for the normal as it is undefined...
Maybe you could preprocess the mesh by using the -hm option to attempt to heal the mesh.

**Comment by kmacolini** [comment]
Hi @ahmedmetin-
Did you resolve this issue? I am having the same problem currently. I tried to preprocess with heal_normals(), but I did not notice any changes in the resulting .stl file. I might be doing something wrong. Thank you. @frongere
