### ISSUE TITLE
Converting - extension "dat" not found

### ISSUE THREAD

**Issue by uzayr123** [LHEEA/meshmagick#14]
Attempting to convert .stl to .dat using the command line, mesh reads in fine, but throws the error
OSError: Extension "dat" is not known.
Looking to use this to then implement with NEMOH.

Unsure if this is user error. 
Help appreciated

**Comment by mancellin** [comment]
Giving only the extension is ambiguous in this case, you need to specify the format with the option `-ofmt`. In your case you'll need `-ofmt nemoh` or `-ofmt mar`.
 See https://lheea.github.io/meshmagick/command_line/cli_reference.html.

By the way, @frongere, I'm curious, what does `mar` stand for?

**Comment by frongere** [comment]
Correct Matthieu :)
Concerning the .mar extension, it was used for mesh files used in Aqua+, the core on which Nemoh is mostly based and written by Gerard Delohommeau at LHEEA lab.
