### ISSUE TITLE
Hydrostatics for fully submerged body.

### ISSUE THREAD

**Issue by akeeste** [LHEEA/meshmagick#19]
This issue relates exactly to #7 . I am having the same issue and would like to work around it. I am also using fully submerged body and have dug into the error a bit. When the hydrostatics class is initialized, it splits the full mesh into the lower portion and the 'clipped mesh' (crown mesh) that represents the portion of the body above the water. The crown mesh is initialized as empty with no vertices / faces, and they are added in mesh_clipper._clip_crown_by_plane(). If the mesh is fully submerged, no vertices/faces end up being added and meshmagick attempts to create a meshmagick.Mesh() with no vertices/faces. This ultimately fails with an assert error. Can meshmagick catch this error and avoid creating a clipped mesh altogether? then it can return 0 stiffness and the rest of the desired properties from the Hydrostatics module.

I am currently interested in the displaced volume, center of buoyancy, and hydrostatic stiffness. When calling meshmagick.Hydrostatics, I can catch this error and assume that the stiffness is zero for a submerged body. The displaced volume can be calculated with the meshmagick.mesh.Mesh.volume module. However there seems to be no way to get the center of buoyancy outside of the Hydrostatics module. Can I calculate this with another meshmagick function?

  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\hydrostatics.py", line 165, in __init__
    self._update_hydrostatic_properties()
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\hydrostatics.py", line 564, in _update_hydrostatic_properties
    clipper = MeshClipper(self.mesh, assert_closed_boundaries=True, verbose=False)
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\mesh_clipper.py", line 37, in __init__
    self._update()
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\mesh_clipper.py", line 114, in _update
    self._clip()
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\mesh_clipper.py", line 751, in _clip
    self._clip_crown_by_plane()
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\mesh_clipper.py", line 665, in _clip_crown_by_plane
    clipped_crown_mesh = Mesh(vertices, crown_faces)
  File "C:\Users\akeeste\Anaconda3\envs\py37\lib\site-packages\meshmagick\mesh.py", line 409, in __init__
    assert np.array(faces).shape[1] == 4
IndexError: tuple index out of range

**Comment by ryancoe** [comment]
@akeeste - Not sure if you already solved this, but I recently stumbled across a workable solution using the methods in `meshmagick` that generate `RigidBodyInertia` objects. For example, you can use the `eval_plain_mesh_inertias` method as follows.

https://github.com/LHEEA/meshmagick/blob/0d214f94d444c55cfc2ecce830e57de08793bf2f/meshmagick/mesh.py#L1965

```python
from meshmagick.mmio import load_mesh
from meshmagick.mesh import Mesh
import pygmsh
import pytest

r = 1
geom = pygmsh.opencascade.Geometry()
sphere = geom.add_ball([0,0,-1], r)
mshArgs = ['-clscale', str(0.25),
           '-clcurv', str(360/50)]

fbname = 'mmtest'
_ = pygmsh.generate_mesh(geom,
                            dim=2,
                            extra_gmsh_arguments=mshArgs,
                            remove_lower_dim_cells=True,
                            geo_filename=fbname + '.geo',
                            msh_filename=fbname + '.stl',
                            mesh_file_type="stl")

mesh = Mesh(*load_mesh(fbname + '.stl', 'stl'))


inertia = mesh.eval_plain_mesh_inertias()
cob = inertia.gravity_center

assert pytest.approx(-1, rel=1e-4) == cob[2]
```

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5589887/110194564-0be64800-7df6-11eb-8c11-56b5574c7c55.png">

**Comment by akeeste** [comment]
@ryancoe Thanks for pointing this out! I hadn't found a solution for this yet, this is very helpful. Now in the instance where the body is fully submerged, I can catch the hydrostatics error and just use the mesh to get the cb.

**Comment by ryancoe** [comment]
@akeeste - Happy to help. Would you mind posting an example of your workflow here? Or (even better) submit a PR that would make this seamless?
