### ISSUE TITLE
ModuleNotFoundError: No module named 'meshmagick_cli'

### ISSUE THREAD

**Issue by battuta** [LHEEA/meshmagick#27]
Hi, I am getting this error when I am trying to run the code "meshmagick".

`Microsoft Windows [Version 10.0.19042.631]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Windows\system32>meshmagick
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\meshmagick-script.py", line 11, in <module>
    load_entry_point('meshmagick==2.1.1', 'console_scripts', 'meshmagick')()
  File "c:\users\User\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\User\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\User\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\User\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'meshmagick_cli'
`

**Comment by frongere** [comment]
My advice: 

- use the miniconda Python distribution instead of a system install
- install meshmagick using pip (`pip install .` while in the meshmagick directory)

**Comment by battuta** [comment]
Trying to install conda 4.2 > failed
![Untitled](https://user-images.githubusercontent.com/33733592/117398057-2330d700-af06-11eb-8ccc-599d8d7f7fda.png)



Trying to install meshmagick without conda 4.2 > failed
![Untitled2](https://user-images.githubusercontent.com/33733592/117398140-5f643780-af06-11eb-9a1e-b7061f5cb894.png)

**Comment by frongere** [comment]
The point was to install miniconda to get a Python 3.X distribution then install meshmagick using `pip install .` or `pip install -e .` if you want to be able to update meshmagick by only pulling the git repository on your local machine. One of these commands has to be run in the meshmagick root directory, where the setup.py file is located.

Don't use the `conda install` command as it is not up to date anymore. I have to refresh the documentation, sorry.

**Comment by battuta** [comment]
It works now. THANK YOU!

We didn’t have these issues, one year ago, when we dealt with _meshmagick_ for the first time.  So, we hope you Update the documentations. Nevertheless, you are doing a great job! That really helped us before in our graduation project which was on marine engineering field. 

Keep up the good work. 💪

**Comment by frongere** [comment]
Thank you! Happy to see it helps :+1: 
New features to come soon...

**Comment by dforbush2** [comment]
I am seeing an identical error, but 'pip install .' did not resolve the problem. 
I have tried cloning the repository and running 'python setup.py install', and gotten this same error.
I have also tried the pip install method, as well as conda install (but this latter is not expected to work). 

I have attempted the above in both a py37 and py38 environment.

**Comment by russell-sealand** [comment]
> The point was to install miniconda to get a Python 3.X distribution then install meshmagick using `pip install .` or `pip install -e .` if you want to be able to update meshmagick by only pulling the git repository on your local machine. One of these commands has to be run in the meshmagick root directory, where the setup.py file is located.
> 
> Don't use the `conda install` command as it is not up to date anymore. I have to refresh the documentation, sorry.

After following these instructions, I installed the latest Miniconda with Python 3.9, but still no success. I get the following error:

(base) PS C:\temp2> meshmagick
Traceback (most recent call last):
  File "d:\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\miniconda3\Scripts\meshmagick.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'meshmagick_cli'

**Comment by mancellin** [comment]
I can confirm that the cli is broken when the package is installed with
```
pip install https://github.com/LHEEA/meshmagick/archive/master.zip
```
or
```
pip install .
```

It seems to work only when the package is installed in editable mode:
```
pip install -e .
```

I guess the reason is that with a normal (non-editable) installation, only the content of the `meshmagick` directory is actually installed, so Python can't find `meshmagick_cli` in the parent directory.

**Comment by russell-sealand** [comment]
> I can confirm that the cli is broken when the package is installed with
> 
> ```
> pip install https://github.com/LHEEA/meshmagick/archive/master.zip
> ```
> 
> or
> 
> ```
> pip install .
> ```
> 
> It seems to work only when the package is installed in editable mode:
> 
> ```
> pip install -e .
> ```
> 
> I guess the reason is that with a normal (non-editable) installation, only the content of the `meshmagick` directory is actually installed, so Python can't find `meshmagick_cli` in the parent directory.

Thanks for the response, for my benefit, please can you detail the complete command string required for installation?

When I try: <pip install -e https://github.com/LHEEA/meshmagick/archive/master.zip>

I get the following error:

> ERROR: https://github.com/LHEEA/meshmagick/archive/master.zip is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

>

**Comment by mancellin** [comment]
* With `git`:
```
git clone https://github.com/LHEEA/meshmagick.git
cd meshmagick
pip install -e .
```

* Without `git`:
Download `https://github.com/LHEEA/meshmagick/archive/master.zip` and unzip it. In the directory `meshmagick-master` run
```
pip install -e .
```

**Comment by russell-sealand** [comment]
Success! Many thanks! Now I can finally try MeshMagick 2 years later! :boom:

Hopefully the Readme.rst gets updated to reflect this installation process!

**Comment by mancellin** [comment]
> Hopefully the Readme.rst gets updated to reflect this installation process!

Now that #40 has been merged, the command in the README should work directly, no need for `-e` anymore.
