### ISSUE TITLE
conda/pip installation issues

### ISSUE THREAD

**Issue by dav-og** [LHEEA/meshmagick#28]
After following the recommended installation method:
  ```shell
  > conda install -c frongere meshmagick
  ```
Importing the mesh module results in the following error:
  ```shell
  > import meshmagick.mesh as mmm
  > ...
  > ModuleNotFoundError: No module named 'vtkCommonCorePython'
  ```

Some colleagues have also reported that `pip install meshmagick` is returning `"No matching distribution found"`

Hence, it seems like the meshmagick versions available via conda/pip are not up to date.

The current installation approach we are working with is:
  ```shell
  > git clone https://github.com/LHEEA/meshmagick
  > cd meshmagick
  ```
Then, if you intend to modify the source code:
  ```shell
  > python setup.py develop
  ```
if not:
  ```shell
  > pip install -e .
  ```

**Comment by ryancoe** [comment]
I have not been able to install `meshmagick` via `conda` for a while. I guess this is because I'm using conda v4.10.1. It seems this is a known issue (https://lheea.github.io/meshmagick/install/install.html#installing-with-conda), as the docs recommend using v4.2?

 I've been using `pip`, e.g.,:

```bash
conda install <all the requirements>
pip install git+https://github.com/LHEEA/meshmagick.git@2.1.1
```

**Comment by cmichelenstrofer** [comment]
Are there any plans to fix this? It would be great if meshmagick was in PyPi so that you could do `pip install meshmagick`. It not being in PyPi is also an issue when trying to include it in another package (I couldn't figure out how to include meshmagick in the setup.cfg file).

**Comment by kasia129** [comment]
I'm trying to install Meshmagick through

```
> git clone https://github.com/LHEEA/meshmagick
> cd meshmagick
> pip install -e .
```
as suggested by @dav-og. Installation is successful, however, when trying to run it, I'm getting this message:

> ModuleNotFoundError: No module named 'vtkCommonCorePython'

Is there anything else I can try?

**Comment by cmichelenstrofer** [comment]
@kasia129 Which Python version are you using? I had a similar problem while trying to use Python 3.10. VTK is still not available for Python 3.10 and I had to downgrade it to Python 3.9. Creating a clean Python 3.9 environment and then installing meshmagick worked for me.

**Comment by dav-og** [comment]
I've also seen this error - I'm using 3.7 👍
Apologies for missing that out in the other post ;)

**Comment by kasia129** [comment]
On one machine I have Python 3.7 - that one gives errors. On a different machine I have 3.9, no problems there - will try to setup a new environment and report back, hope that will solve the issue.
